### ISSUE TITLE
Error in "Tuning hyperparameters with grid search"..

### ISSUE THREAD

**Issue by coforfe** [PacktPublishing/Forecasting-Time-Series-Data-with-Prophet-Second-Edition#1]
Hi,

Just a quick note to hightlight that in page 236  in epigraph **`Tuning hyperparameters with grid search`** in figure `13.8 - Prophet grid search parameters` there seems to be an error:

- Column `seasonality_prior_scale` is duplicated.

Thanks,
Carlos.

**Comment by raffg** [comment]
Hi Carlos, thanks for the note! I'll alert the publisher to the error. The correct name for the duplicate column should be `holidays_prior_scale`:
![Fig 13 8](https://github.com/PacktPublishing/Forecasting-Time-Series-Data-with-Prophet-Second-Edition/assets/20135094/415bfe48-ae01-4ab5-b974-8fb37f176a31)
